--- #YAML:1.0
name:                App-Context
version:             0.966
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    App::Options:                  0.01
    Class::Data::Inheritable:      0.01
    Compress::Zlib:                0.01
    Data::Dumper:                  0.01
    Date::Format:                  0.01
    Date::Parse:                   0.01
    Devel::StackTrace:             0.01
    Exception::Class:              0.01
    MIME::Base64:                  2.1
    Storable:                      0.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
