--- #YAML:1.0
name:                App-Context
version:             0.9661
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    App::Options:                  0.01
    CGI:                           0.01
    CGI::Carp:                     0.01
    Class::Data::Inheritable:      0.01
    Compress::Zlib:                0.01
    Data::Dumper:                  0.01
    Date::Format:                  0.01
    Date::Parse:                   0.01
    Devel::StackTrace:             0.01
    Digest::SHA:                   0.01
    Exception::Class:              0.01
    HTTP::Status:                  0.01
    IO::Handle:                    0.01
    IO::Socket:                    0.01
    IO::Socket::INET:              0.01
    MIME::Base64:                  2.1
    Pod::Checker:                  0.01
    POSIX:                         0.01
    Socket:                        0.01
    Storable:                      0.01
    Sys::Hostname:                 0.01
    Test::More:                    0.01
    Time::HiRes:                   0.01
    XML::Simple:                   0.01
    YAML:                          0.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
