# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         App-Context
version:      0.964
version_from: 
installdirs:  site
requires:
    App::Options:                  0.01
    Class::Data::Inheritable:      0.01
    Compress::Zlib:                0.01
    Data::Dumper:                  0.01
    Date::Format:                  0.01
    Date::Parse:                   0.01
    Devel::StackTrace:             0.01
    Exception::Class:              0.01
    MIME::Base64:                  2.1
    Storable:                      0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
